import { z } from 'zod';

// Thông báo lỗi zod bằng tiếng Việt cho cả server lẫn client
z.config(z.locales.vi());

export * from './money.js';
export * from './csv.js';
export * from './order-math.js';
export * from './local-date.js';
export * from './text.js';
export * from './vietqr.js';
export * from './banks.js';
export * from './cart.js';
export * from './inventory-math.js';
export * from './import-draft.js';
export * from './return-math.js';
export * from './ean.js';
export * from './labels.js';
export * from './supplier-return-math.js';
export * from './supplier-return-draft.js';
export * from './types.js';
export * from './schemas/common.js';
export * from './schemas/category.js';
export * from './schemas/product.js';
export * from './schemas/product-unit.js';
export * from './schemas/order.js';
export * from './schemas/settings.js';
export * from './schemas/supplier.js';
export * from './schemas/import.js';
export * from './schemas/stocktake.js';
export * from './schemas/customer.js';
export * from './schemas/list-filters.js';
export * from './schemas/report.js';
export * from './schemas/backups.js';
export * from './schemas/overview.js';
export * from './schemas/return.js';
export * from './schemas/supplier-return.js';
export * from './schemas/label.js';
export * from './schemas/remote.js';
export * from './list-filters.js';
export * from './product-csv.js';
